"""Catalogo de restaurantes de Ciudad de Guatemala para importacion Neo4j."""

from __future__ import annotations

import random

ZONAS = [
    "Zona 10",
    "Zona 14",
    "Zona 15",
    "Zona 16",
    "Zona 5",
    "Zona 11",
    "Zona 4",
    "Zona 1",
]

CUISINES = [
    "Japonesa",
    "Italiana",
    "Guatemalteca",
    "Internacional",
    "Mexicana",
    "Peruana",
    "Americana",
    "Mediterranea",
    "Coreana",
    "China",
    "Francesa",
    "India",
    "Steakhouse",
    "Mariscos",
    "Cafe",
]

AMBIENTES = [
    "casual",
    "elegante",
    "romantico",
    "familiar",
    "trendy",
    "tranquilo",
    "nocturno",
    "brunch",
]

KNOWN = [
    "Sushi Ito",
    "Tamarindos",
    "Hibachi",
    "Pecorino",
    "Kaffeine",
    "Bottega Foresto",
    "Viu Bistro",
    "El Portal",
    "Casa del Ángel",
    "Frida Kahlo",
    "Porcino",
    "Café Flor",
    "Café Barista",
    "Café León",
    "San Martín",
    "Tre Fratelli",
    "La Esquina",
    "Los Tres Tiempos",
    "El Cielo",
    "Café de Imeri",
    "Café Flor de Lis",
    "Café León de Oro",
    "Café Barista Zona 10",
    "Café León Zona 14",
    "Café Barista Zona 15",
    "Rincón del Steak",
    "El Establo",
    "La Pampa",
    "El Rincón del Bife",
    "Café de la Paix",
    "Café Flor de Lis Zona 10",
    "Café León Zona 16",
    "Café Barista Zona 5",
    "Café León Zona 11",
    "Café Flor Zona 4",
    "Café Barista Zona 1",
    "La Veranda",
    "El Patio",
    "Café del Parque",
    "Café Central",
    "Café del Museo",
    "Café de la Plaza",
    "Café del Mercado",
    "Café del Río",
    "Café del Lago",
    "Café del Bosque",
    "Café del Sol",
    "Café de la Luna",
    "Café del Mar",
    "Café del Valle",
    "Café de la Montaña",
    "Café del Pueblo",
    "Café de la Ciudad",
    "Café del Barrio",
    "Café de la Esquina",
    "Café del Centro",
    "Café de la Avenida",
    "Café del Boulevard",
    "Café de la Calle",
    "Café del Jardín",
    "Café de la Terraza",
    "Café del Mirador",
    "Café de la Colina",
    "Café del Horizonte",
    "Café de la Brisa",
    "Café del Atardecer",
    "Café de la Mañana",
    "Café del Mediodía",
    "Café de la Tarde",
    "Café de la Noche",
    "Café del Alba",
    "Café del Crepúsculo",
    "Café de la Estrella",
    "Café del Cometa",
    "Café de la Galaxia",
    "Café del Universo",
    "Café de la Nebulosa",
    "Café del Planeta",
    "Café de la Órbita",
    "Café del Cosmos",
    "Café de la Vía Láctea",
    "Café del Eclipse",
    "Café de la Aurora",
    "Café del Amanecer",
    "Café de la Bruma",
    "Café del Niebla",
    "Café de la Lluvia",
    "Café del Arcoíris",
    "Café de la Tormenta",
    "Café del Trueno",
    "Café de la Centella",
    "Café del Relámpago",
    "Café de la Chispa",
    "Café del Fuego",
    "Café de la Llama",
    "Café del Carbón",
    "Café de la Brasa",
    "Café del Humo",
    "Café de la Ceniza",
    "Café del Volcán",
    "Café de la Lava",
    "Café del Magma",
    "Café de la Piedra",
    "Café del Granito",
    "Café de la Roca",
    "Café del Cristal",
    "Café de la Gema",
    "Café del Oro",
    "Café de la Plata",
    "Café del Cobre",
    "Café de la Perla",
    "Café del Diamante",
    "Café de la Esmeralda",
    "Café del Rubí",
    "Café de la Zafiro",
    "Café del Topacio",
    "Café de la Amatista",
    "Café del Ópalo",
    "Café de la Turquesa",
    "Café del Jade",
    "Café de la Obsidiana",
    "Café del Ámbar",
    "Café de la Coral",
    "Café del Marfil",
    "Café de la Nácar",
    "Café del Concha",
    "Café de la Ostra",
    "Café del Almeja",
    "Café de la Mejillón",
    "Café del Camarón",
    "Café de la Langosta",
    "Café del Cangrejo",
    "Café de la Pulpo",
    "Café del Calamar",
    "Café de la Sardina",
    "Café del Atún",
    "Café de la Salmón",
    "Café del Trucha",
    "Café de la Bacalao",
    "Café del Merluza",
    "Café de la Lubina",
    "Café del Dorada",
    "Café de la Rodaballo",
    "Café del Lenguado",
    "Café de la Rape",
    "Café del Besugo",
    "Café de la Caballa",
    "Café del Jurel",
    "Café de la Anchoa",
    "Café del Boquerón",
    "Café de la Arenque",
    "Café del Salmonete",
    "Café de la Platija",
    "Café del Fletán",
    "Café de la Merluzuela",
    "Café del Bonito",
    "Café de la Cabracho",
    "Café del Rascacio",
    "Café de la Congrio",
    "Café del Morena",
    "Café de la Anguila",
    "Café del Esturión",
    "Café de la Caviar",
    "Café del Beluga",
    "Café de la Osetra",
    "Café del Sevruga",
    "Café de la Lumpo",
    "Café del Huevas",
    "Café de la Moluga",
    "Café del Arenque",
    "Café de la Caballa",
    "Café del Sardina",
    "Café de la Anchoa",
    "Café del Boquerón",
    "Café de la Platija",
    "Café del Fletán",
    "Café de la Merluzuela",
    "Café del Bonito",
    "Café de la Cabracho",
    "Café del Rascacio",
    "Café de la Congrio",
    "Café del Morena",
    "Café de la Anguila",
    "Café del Esturión",
    "Café de la Caviar",
    "Café del Beluga",
    "Café de la Osetra",
    "Café del Sevruga",
    "Café de la Lumpo",
    "Café del Huevas",
    "Café de la Moluga",
    "La Pampa Grill",
    "El Establo Steak",
    "Rincón Steak House",
    "Mariscos del Puerto",
    "La Cevichería",
    "El Pescador",
    "Tacos del Centro",
    "Antojitos Guate",
    "Pizza Napoli",
    "Trattoria Roma",
    "Osteria Milano",
    "Ramen House GT",
    "Izakaya Zona 10",
    "Bulgogi House",
    "Kimchi Bar",
    "Curry Palace",
    "Tandoor Express",
    "Bistro Francés",
    "Brasserie 14",
    "Wine & Dine",
    "Tapas Barcelona",
    "Churrasco Real",
    "Asado Norte",
    "Pollo Campero Bistro",
    "Milanesa Club",
    "Empanada Lab",
    "Arepa Station",
    "Ceviche 360",
    "Nikkei Fusion",
    "Dim Sum GT",
    "Wok Master",
    "Pho Saigon",
    "Banana Leaf",
    "Green Bowl",
    "Veggie Corner",
    "Smoothie Lab",
    "Brunch & Co",
    "Morning Glory",
    "Eggs Benedict GT",
    "Pancake Factory",
    "Donut District",
    "Ice Cream Social",
    "Helado Artesanal",
    "Chocolate Room",
    "Postre Boutique",
    "Panadería San José",
    "Croissant House",
    "Bagel Bar GT",
    "Sandwich Society",
    "Burger Lab",
    "Smash Burger GT",
    "Hot Dog Republic",
    "Alitas Express",
    "Wings & Beer",
    "Sports Bar 16",
    "Rooftop Lounge",
    "Sky Bar GT",
    "Cocktail Club",
    "Mezcalería Centro",
    "Tequila House",
    "Wine Bar Zona 10",
    "Craft Beer GT",
    "Microbrew 5",
    "Gastro Pub 11",
    "Food Hall GT",
    "Mercado Gastronómico",
    "Food Truck Park",
    "Comedor Popular",
    "Cocina de Autor",
    "Chef Table GT",
    "Mesa Degustación",
    "Omakase Room",
    "Sushi Bar 14",
    "Teppanyaki GT",
    "Yakitori Alley",
    "BBQ Smokehouse",
    "Pit Master GT",
    "Carne Asada House",
    "Tortillería Moderna",
    "Pupusería Gourmet",
    "Tamal Boutique",
    "Kakao Kitchen",
    "Cacao Lab",
    "Farm to Table GT",
    "Huerto Bistro",
    "Organic Plate",
    "Zero Waste Kitchen",
    "Slow Food GT",
    "Comfort Kitchen",
    "Soul Food GT",
    "Southern Grill",
    "Texas BBQ GT",
    "Nashville Hot",
    "Creole Kitchen",
    "Cajun Spot",
    "New Orleans GT",
    "Creperie Paris",
    "Gelato Italiano",
    "Gnocchi House",
    "Risotto Room",
    "Lasagna Lab",
    "Carbonara Club",
    "Amatriciana Bar",
    "Porchetta GT",
    "Prosciutto Bar",
    "Antipasti House",
    "Mozzarella Bar",
    "Burrata Bistro",
    "Truffle Room",
    "Mushroom Bistro",
    "Forest Kitchen",
    "Garden Plate",
    "Terraza Verde",
    "Jardín Secreto",
    "Patio Colonial",
    "Casona Bistro",
    "Mansión 10",
    "Villa Gourmet",
    "Palacio del Sabor",
    "Reina del Café",
    "Rey del Taco",
    "Príncipe Ramen",
    "Duquesa Pasta",
    "Conde Ceviche",
    "Barón Burger",
    "Condesa Brunch",
    "Marquesa Wine",
    "Vizconde Grill",
    "Gran Duque Steak",
    "Imperio Nikkei",
    "Legado Maya",
    "Origen Guatemala",
    "Raíces Kitchen",
    "Sabores del Valle",
    "Altiplano Bistro",
    "Volcán Grill",
    "Atitlán Seafood",
    "Petén Explorer",
    "Antigua Fusion",
    "Colonial Table",
    "Centro Histórico Café",
    "Mercado Central Grill",
    "Terminal Gourmet",
    "Aeropuerto Bistro",
    "Hotel Rooftop GT",
    "Lobby Lounge",
    "Pool Bar Kitchen",
    "Spa Cuisine",
    "Gym Fuel",
    "Runner's Plate",
    "Cyclist Café",
    "Yoga Kitchen",
    "Wellness Bowl",
    "Protein Lab",
    "Keto Kitchen GT",
    "Vegan Delight",
    "Plant Based GT",
    "Raw Bar",
    "Juice Cleanse",
    "Detox Kitchen",
    "Superfood Lab",
    "Acai Bowl GT",
    "Poke House",
    "Hawaiian Plate",
    "Aloha Grill",
    "Pacific Rim",
    "Island Kitchen",
    "Caribeño Spot",
    "Cubano GT",
    "Havana Nights",
    "Salsa Kitchen",
    "Mambo Grill",
    "Tango Bistro",
    "Buenos Aires GT",
    "Chimichurri House",
    "Parrilla Argentina",
    "Uruguay Grill",
    "Chilean Flame",
    "Andes Kitchen",
    "Lima Fusion",
    "Machu Picchu Bistro",
    "Quinoa Bowl",
    "Amazon Plate",
    "Rainforest Kitchen",
    "Jungle Spice",
    "Tropicalia",
    "Mango Mango",
    "Piña Colada Kitchen",
    "Coconut Grove",
    "Palm Tree Bistro",
    "Sunset Grill GT",
    "Horizon Dining",
    "Twilight Terrace",
    "Midnight Kitchen",
    "After Hours GT",
    "Late Night Bites",
    "24h Comedor",
    "Desayuno Express",
    "Almuerzo Ejecutivo",
    "Cena de Negocios",
    "Power Lunch GT",
    "Boardroom Bistro",
    "Corporate Kitchen",
    "Startup Café",
    "Tech Campus Food",
    "Innovation Kitchen",
    "Digital Dining",
    "Cloud Kitchen GT",
    "Ghost Kitchen Hub",
    "Delivery Only GT",
    "Takeout Masters",
    "Pickup Point",
    "Drive Thru Gourmet",
    "Curbside Kitchen",
    "Fast Casual GT",
    "Quick Bite",
    "Speed Grill",
    "Express Pasta",
    "Rapid Ramen",
    "Flash Sushi",
    "Instant Tacos",
    "Turbo Burger",
    "Hyper Bowl",
    "Mega Burrito",
    "Ultra Wings",
    "Max Pizza",
    "Pro Sandwich",
    "Elite Dining GT",
    "Exclusive Table",
    "Members Only Kitchen",
    "Private Chef GT",
    "Reservation Only",
    "Hidden Gem GT",
    "Speakeasy Kitchen",
    "Underground Bistro",
    "Back Alley Grill",
    "Side Street Tacos",
    "Corner Café GT",
    "Neighborhood Bistro",
    "Local Favorite",
    "Community Kitchen",
    "Family Table GT",
    "Kids Friendly Spot",
    "Playground Café",
    "Pet Friendly Bistro",
    "Dog Park Grill",
    "Cat Café GT",
    "Bookstore Kitchen",
    "Library Lounge",
    "Art Gallery Bistro",
    "Museum Café GT",
    "Theater Dining",
    "Cinema Snacks GT",
    "Concert Hall Food",
    "Stadium Grill",
    "Arena Bites",
    "Golf Club Dining",
    "Tennis Club Kitchen",
    "Yacht Club GT",
    "Marina Seafood",
    "Harbor View",
    "Dockside Grill",
    "Pier Kitchen",
    "Boardwalk Bites",
    "Beach House GT",
    "Coastal Kitchen",
    "Surf & Turf GT",
    "Wave Rider Café",
    "Tide Table",
    "Anchor Bistro",
    "Lighthouse Grill",
    "Captain's Table",
    "Sailor's Kitchen",
    "Pirate's Cove GT",
    "Treasure Island Food",
    "Map Room Dining",
    "Compass Kitchen",
    "Navigator Bistro",
    "Explorer's Plate",
    "Adventure Grill GT",
    "Trail Kitchen",
    "Campfire Dining",
    "Mountain Lodge GT",
    "Summit Bistro",
    "Peak Performance Food",
    "Base Camp Kitchen",
    "Expedition Dining",
    "Safari Grill GT",
    "Savanna Kitchen",
    "Serengeti Spot",
    "Wildlife Bistro",
    "Nature Plate",
    "Eco Lodge Dining",
    "Sustainable GT",
    "Carbon Neutral Kitchen",
    "Green Future Food",
    "Tomorrow Bistro",
    "Next Gen Dining",
    "Future Food Lab",
    "Molecular GT",
    "Science Kitchen",
    "Lab Café",
    "Experiment Bistro",
    "Beta Kitchen",
    "Alpha Grill",
    "Gamma Dining",
    "Delta Food",
    "Omega Bistro",
    "Sigma Kitchen",
    "Lambda Grill",
    "Theta Dining",
    "Phi Food GT",
    "Psi Bistro",
    "Chi Kitchen",
    "Rho Grill",
    "Nu Dining",
    "Mu Food",
    "Pi Kitchen GT",
    "Tau Bistro",
    "Iota Grill",
    "Kappa Dining",
    "Eta Food",
    "Zeta Kitchen",
    "Xi Bistro GT",
]

_SUFFIXES = [
    "Bistro",
    "Kitchen",
    "Grill",
    "House",
    "Room",
    "Bar",
    "Lounge",
    "Corner",
    "Social",
    "Lab",
    "Club",
    "Terrace",
    "Garden",
    "Table",
    "Plate",
]

_PREF_POOL = [
    "casual",
    "gourmet",
    "tradicional",
    "moderno",
    "aventurero",
    "explorador",
    "equilibrado",
    "indulgente",
    "social_pareja",
    "social_grupo",
    "social_familia",
    "sabor_umami",
    "sabor_picante",
    "sabor_fresco",
    "pref_japonesa",
    "pref_italiana",
    "pref_guatemalteca",
    "slow_food",
    "street_food",
    "premium",
    "comfort_food",
    "trendy",
    "aesthetic",
    "romantic",
    "family_friendly",
    "nightlife",
    "brunch",
    "exclusive",
    "fast_service",
    "tranquil",
    "elegant",
    "smoky",
    "saludable",
    "contundente",
]


def _cuisine_prefs(cocina: str) -> dict[str, float]:
    base: dict[str, float] = {"equilibrado": 0.55}
    mapping = {
        "Japonesa": {"pref_japonesa": 1.0, "sabor_umami": 0.85, "gourmet": 0.7},
        "Italiana": {"pref_italiana": 1.0, "slow_food": 0.65, "romantic": 0.5},
        "Guatemalteca": {"pref_guatemalteca": 1.0, "tradicional": 0.8, "contundente": 0.75},
        "Mexicana": {"street_food": 0.7, "sabor_picante": 0.75},
        "Peruana": {"explorador": 0.65, "sabor_fresco": 0.7},
        "Mariscos": {"gourmet": 0.6, "sabor_fresco": 0.8},
        "Steakhouse": {"contundente": 0.9, "premium": 0.75, "smoky": 0.7},
        "Cafe": {"brunch": 0.85, "casual": 0.7, "aesthetic": 0.6},
    }
    base.update(mapping.get(cocina, {"moderno": 0.5}))
    return base


def _ambiente_prefs(ambiente: str) -> dict[str, float]:
    mapping = {
        "casual": {"casual": 0.9, "fast_service": 0.6},
        "elegante": {"elegant": 0.9, "gourmet": 0.7, "exclusive": 0.55},
        "romantico": {"romantic": 0.95, "slow_food": 0.6},
        "familiar": {"family_friendly": 0.95, "comfort_food": 0.7},
        "trendy": {"trendy": 0.9, "aesthetic": 0.75, "nightlife": 0.4},
        "tranquilo": {"tranquil": 0.9, "slow_food": 0.55},
        "nocturno": {"nightlife": 0.9, "social_grupo": 0.65},
        "brunch": {"brunch": 0.95, "aesthetic": 0.5},
    }
    return mapping.get(ambiente, {"casual": 0.5})


def _build_prefs(cocina: str, ambiente: str, precio: int, rating: float) -> dict[str, float]:
    prefs = _cuisine_prefs(cocina)
    for k, v in _ambiente_prefs(ambiente).items():
        prefs[k] = max(prefs.get(k, 0.0), v)
    if precio >= 350:
        prefs["premium"] = max(prefs.get("premium", 0.0), 0.85)
        prefs["exclusive"] = max(prefs.get("exclusive", 0.0), 0.7)
    elif precio <= 80:
        prefs["ahorrador"] = max(prefs.get("ahorrador", 0.0), 0.8)
    if rating >= 4.6:
        prefs["gourmet"] = max(prefs.get("gourmet", 0.0), 0.75)
    extra = random.sample(_PREF_POOL, k=3)
    for p in extra:
        prefs[p] = max(prefs.get(p, 0.0), round(random.uniform(0.35, 0.75), 2))
    return {k: round(min(1.0, v), 2) for k, v in prefs.items()}


def _seed_restaurants() -> list[dict]:
    return [
        {
            "id": "r1",
            "nombre": "Sushi Ito",
            "zona": "Zona 10",
            "rating": 4.8,
            "precio": 120,
            "cocina": "Japonesa",
            "ambiente": "elegante",
            "prefs": {
                "gourmet": 0.9,
                "aventurero": 0.7,
                "explorador": 0.6,
                "indulgente": 0.8,
                "sabor_umami": 0.95,
                "pref_japonesa": 1.0,
                "slow_food": 0.75,
                "social_pareja": 0.5,
                "elegant": 0.8,
            },
        },
        {
            "id": "r2",
            "nombre": "La Trattoria",
            "zona": "Zona 10",
            "rating": 4.5,
            "precio": 80,
            "cocina": "Italiana",
            "ambiente": "romantico",
            "prefs": {
                "gourmet": 0.65,
                "tradicional": 0.55,
                "equilibrado": 0.7,
                "pref_italiana": 1.0,
                "slow_food": 0.6,
                "social_pareja": 0.6,
                "social_grupo": 0.5,
                "romantic": 0.7,
            },
        },
        {
            "id": "r3",
            "nombre": "El Fogón",
            "zona": "Zona 4",
            "rating": 4.3,
            "precio": 60,
            "cocina": "Guatemalteca",
            "ambiente": "familiar",
            "prefs": {
                "casual": 0.8,
                "tradicional": 0.85,
                "ahorrador": 0.75,
                "contundente": 0.9,
                "pref_guatemalteca": 1.0,
                "social_familia": 0.7,
                "comfort_food": 0.75,
            },
        },
        {
            "id": "r4",
            "nombre": "Casa Mia",
            "zona": "Zona 1",
            "rating": 4.6,
            "precio": 95,
            "cocina": "Italiana",
            "ambiente": "elegante",
            "prefs": {
                "equilibrado": 0.8,
                "gourmet": 0.55,
                "pref_italiana": 1.0,
                "social_pareja": 0.75,
                "slow_food": 0.5,
                "elegant": 0.65,
            },
        },
    ]


def _generate_catalog() -> list[dict]:
    random.seed(42)
    items = _seed_restaurants()
    used_names = {r["nombre"] for r in items}
    idx = 1
    while len(items) < 214:
        rid = "gt%03d" % idx
        idx += 1
        if rid in {r["id"] for r in items}:
            continue
        nombre = KNOWN[(idx - 2) % len(KNOWN)]
        if nombre in used_names:
            nombre = "%s %s" % (nombre, _SUFFIXES[(idx - 2) % len(_SUFFIXES)])
        used_names.add(nombre)
        zona = ZONAS[(idx - 2) % len(ZONAS)]
        cocina = CUISINES[(idx - 2) % len(CUISINES)]
        ambiente = AMBIENTES[(idx - 2) % len(AMBIENTES)]
        rating = round(random.uniform(3.8, 4.9), 1)
        precio = int(random.uniform(40, 2000) // 5 * 5)
        prefs = _build_prefs(cocina, ambiente, precio, rating)
        items.append(
            {
                "id": rid,
                "nombre": nombre,
                "zona": zona,
                "rating": rating,
                "precio": precio,
                "cocina": cocina,
                "ambiente": ambiente,
                "prefs": prefs,
            }
        )
    return items


RESTAURANTS: list[dict] = _generate_catalog()